### PR TITLE
add active cape functionality

### PR DESCRIPTION
**Pull request by Unis-bit**
Add >active command
Integrate active cape functionality into >rank show & >account show

### CODE REVIEW

**Comment by Chevron9** [comment]
The parts where you pop the author's axtive cape need to be saved back to the file, currenlty they are not.

**Comment by Unis-bit** [comment]
Noted, will update now. Going to try and add in the uh, >win/loss functionality too after this.

**Comment by Chevron9** [comment]
Do you wanna update this to work with the current version?

**Comment by Chevron9** [comment]
closed, inactive

**Pull request closed without merging**
